# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/game_room.ui'
#
# Created by: PyQt5 UI Source generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_gameroom(object):
    def setupUi(self, gameroom):
        gameroom.setObjectName("gameroom")
        gameroom.resize(900, 600)
        self.frame = QtWidgets.QFrame(gameroom)
        self.frame.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 10, 641, 31))
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(140, 270, 611, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.input_line = QtWidgets.QLineEdit(self.frame)
        self.input_line.setGeometry(QtCore.QRect(140, 510, 511, 41))
        self.input_line.setObjectName("input_line")
        self.send_btn = QtWidgets.QPushButton(self.frame)
        self.send_btn.setGeometry(QtCore.QRect(670, 520, 75, 23))
        self.send_btn.setObjectName("send_btn")
        self.lyrics_lbl = QtWidgets.QLabel(self.frame)
        self.lyrics_lbl.setGeometry(QtCore.QRect(120, 110, 631, 131))
        self.lyrics_lbl.setStyleSheet("font: 14pt \"Alef\";")
        self.lyrics_lbl.setObjectName("lyrics_lbl")
        self.exit_btn = QtWidgets.QPushButton(self.frame)
        self.exit_btn.setGeometry(QtCore.QRect(814, 10, 71, 31))
        self.exit_btn.setObjectName("exit_btn")

        self.retranslateUi(gameroom)
        QtCore.QMetaObject.connectSlotsByName(gameroom)

    def retranslateUi(self, gameroom):
        _translate = QtCore.QCoreApplication.translate
        gameroom.setWindowTitle(_translate("gameroom", "Form"))
        self.label.setText(_translate("gameroom", "게임 룸"))
        self.send_btn.setText(_translate("gameroom", "전송"))
        self.lyrics_lbl.setText(_translate("gameroom", "노래가사"))
        self.exit_btn.setText(_translate("gameroom", "나가기"))
