# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/log_in.ui'
#
# Created by: PyQt5 UI Source generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(900, 600)
        self.frame = QtWidgets.QFrame(login)
        self.frame.setGeometry(QtCore.QRect(0, 0, 900, 600))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(370, 70, 251, 51))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(220, 190, 56, 12))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(220, 250, 56, 12))
        self.label_3.setObjectName("label_3")
        self.id_line = QtWidgets.QLineEdit(self.frame)
        self.id_line.setGeometry(QtCore.QRect(330, 160, 231, 41))
        self.id_line.setObjectName("id_line")
        self.pw_line = QtWidgets.QLineEdit(self.frame)
        self.pw_line.setGeometry(QtCore.QRect(330, 230, 231, 41))
        self.pw_line.setObjectName("pw_line")
        self.login_btn = QtWidgets.QPushButton(self.frame)
        self.login_btn.setGeometry(QtCore.QRect(330, 330, 131, 51))
        self.login_btn.setObjectName("login_btn")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.label.setText(_translate("login", "로그인"))
        self.label_2.setText(_translate("login", "아이디"))
        self.label_3.setText(_translate("login", "비밀번호"))
        self.login_btn.setText(_translate("login", "로그인하기"))
